services:
  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./php/ssl/certs:/etc/ssl/certs:ro
      - ./php/ssl/private:/etc/ssl/private:ro
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
